<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.png">
    <title>Simple PHP MVC</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
    .parent-category {
        font-size: 10px;
    }
    .category .child-categories {
        display: none;
    }

    .category:hover .child-categories {
        display:block;
    }
</style>
<body>
<section>
    <nav class="navbar navbar-light bg-light" >
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </nav>
</section>
<section>
    <div style="display: flex; flex-direction: row;align:center; justify-content:space-evenly;margin-top: 40px;background-color: darkblue;margin-bottom: 80px;color: white;">
        <?php foreach ($parentCategories as $category) { ?>
            <div class="category">
                <a href="https://humg.edu.vn/tin-tuc/Pages/default.aspx">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"> <h2> <?php echo $category['name']  ?></h2></button>
                </a>
                <div class="child-categories"  >
                    <?php foreach ($childCategories as $child) { ?>
                        <?php if ($child['parent_id'] == $category['id']) { ?>
                            <?php echo $child['name']  ?>
                        <?php } ?>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>

<section>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://humg.edu.vn/content/tintuc/PublishingImages/qk.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://humg.edu.vn/content/tintuc/PublishingImages/CSVC/PTN/PTN_Dien-dientu/untitled-6.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://humg.edu.vn/content/tintuc/PublishingImages/SuKien/2020/gia%20tri%20cot%20loi%20humg.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
<section>
    <a href="https://humg.edu.vn/tin-tuc/Pages/default.aspx">
        <button class="btn btn-outline-success my-1 my-sm-0" type="submit"><h5 style="color: blue;">GIỚI THIỆU</h5></button>
    </a>
    <div style="display: flex;border-top: 40px;margin-left: 50px">
        <?php foreach ($gioiThieu as $post) { ?>
            <div style="width: 25%;">
                <img style="width: 300px;height: 200px" src="<?php echo $post['thumbnail'] ?>">

                <a href="/humg/detail.php?id=<?php echo $post['id'] ?>"><h6> <?php echo $post['title'] ?></h6></a>
                <p><?php echo $post['content'] ?></p>
            </div>
        <?php } ?>
    </div>
</section>
<section>
    <a href="https://humg.edu.vn/tin-tuc/Pages/default.aspx">
        <button class="btn btn-outline-success my-1 my-sm-0" type="submit"><h5 style="color: blue;">THÔNG BÁO</h5></button>
    </a>
    <div style="display: flex;border-top: 40px;margin-left: 50px">
    <?php foreach ($thongBao as $post) { ?>
        <div style="width: 25%;">
            <img style="width: 300px;height: 200px" src="<?php echo $post['thumbnail'] ?>">

            <a href="/humg/detail.php?id=<?php echo $post['id'] ?>"><h6> <?php echo $post['title'] ?></h6></a>
            <p><?php echo $post['content'] ?></p>
        </div>
    </div>
    <?php } ?>
</section>
    <section>
        <a href="https://humg.edu.vn/tin-tuc/Pages/default.aspx">
            <button class="btn btn-outline-success my-1 my-sm-0" type="submit"><h5 style="color: blue;">BẢN TIN</h5></button>
        </a>
        <div style="display: flex;border-top: 40px;margin-left: 50px">
            <?php foreach ($banTin  as $post) { ?>
            <div style="width: 25%;">
                <img style="width: 300px;height: 200px" src="<?php echo $post['thumbnail'] ?>">

                <a href="/humg/detail.php?id=<?php echo $post['id'] ?>"><h6> <?php echo $post['title'] ?></h6></a>
                <p><?php echo $post['content'] ?></p>
            </div>
        </div>
        <?php } ?>
    </section>
    <section>
        <a href="https://humg.edu.vn/tin-tuc/Pages/default.aspx">
            <button class="btn btn-outline-success my-1 my-sm-0" type="submit"><h5 style="color: blue;">ĐÀO TẠO</h5></button>
        </a>
        <div style="display: flex;border-top: 40px;margin-left: 50px">
            <?php foreach ($daoTao as $post) { ?>
            <div style="width: 25%;">
                <img style="width: 300px;height: 200px" src="<?php echo $post['thumbnail'] ?>">

                <a href="/humg/detail.php?id=<?php echo $post['id'] ?>"><h6> <?php echo $post['title'] ?></h6></a>
                <p><?php echo $post['content'] ?></p>
            </div>
        </div>
        <?php } ?>
    </section>
</body>

</html>